config/routes.rb
SlamStationNation::Application.routes.draw do
  root 'static#home'

  get '/slam' => 'slam_jams#slam', :as => 'slam'

  # Toggles likes/dislikes for the givem slam_jam
  post 'slam/:id/like' => 'slam_jams#like', :as => 'like_slam'

  # Toggles dislikes/undislikes for the given slam_jam
  post 'slam/:id/dislike' => 'slam_jams#dislike', :as => 'dislike_slam'

  namespace :admin do
    root 'slam_jams#index'

    resources :slam_jams, except: [:show]
  end
end

app/models/admin.rb
module Admin
  def self.table_name_prefix
    'admin_'
  end
end

app/models/slam_jam.rb
class SlamJam < ActiveRecord::Base
  has_many :views, dependent: :destroy
  has_many :users, through: :views

  validates :youtube_id, uniqueness: true, presence: true

  scope :curated, -> { where(approved: true) }

  scope :nth, -> (n) { offset(n).first }
  scope :random, -> { nth(Random.rand(count)) }

  scope :unwatched_by, lambda { |user|
    where(
      <<-SQL
        id NOT IN (SELECT slam_jams.id FROM slam_jams
                   JOIN views ON slam_jams.id = views.slam_jam_id
                   WHERE views.user_id = #{user.id})
      SQL
    )
  }
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :views, dependent: :destroy
  has_many :slam_jams, through: :views

  recommends :slam_jams

  def slam!(slam_jam)
    View.find_or_create_by(slam_jam: slam_jam, user: self).touch
  end

  def desirable_slam_jams
    # Try to return curated SlamJams the user hasn't seen yet
    filtered = SlamJam.curated.unwatched_by(self)
    return filtered if filtered.any?

    # Try to return SlamJams the user hasn't seen yet
    filtered = SlamJam.unwatched_by(self)
    return filtered if filtered.any?

    # Try to return SlamJams the user hasn't seen today
    filtered = slam_jams.where('views.updated_at < ?', 1.day.ago)
    return filtered if filtered.any?

    # Return the least recently viewed half of the slam jams
    slam_jams.order('views.updated_at ASC').limit((SlamJam.count / 2.0).ceil)
  end
end

app/models/view.rb
class View < ActiveRecord::Base
  belongs_to :user
  belongs_to :slam_jam
end

app/controllers/admin/slam_jams_controller.rb
class Admin::SlamJamsController < ApplicationController
  http_basic_authenticate_with name: 'admin',
                               password: Rails.configuration.admin_password
  before_action :set_slam_jam, only: [:show, :edit, :update, :destroy]

  respond_to :json, :html

  # GET /admin/slam_jams
  # GET /admin/slam_jams.json
  def index
    @slam_jams = SlamJam.all
  end

  # GET /admin/slam_jams/new
  def new
    @slam_jam = SlamJam.new
  end

  # GET /admin/slam_jams/1/edit
  def edit
  end

  # POST /admin/slam_jams
  # POST /admin/slam_jams.json
  def create
    @slam_jam = SlamJam.new(slam_jam_params)

    flash[:notice] = 'Slam Jam added.' if @slam_jam.save

    respond_with @slam_jam, location: admin_slam_jams_url
  end

  # PATCH/PUT /admin/slam_jams/1
  # PATCH/PUT /admin/slam_jams/1.json
  def update
    flash[:notice] = 'Slam Jam updated.' if @slam_jam.update(slam_jam_params)

    respond_with @slam_jam, location: admin_slam_jams_url
  end

  # DELETE /admin/slam_jams/1
  # DELETE /admin/slam_jams/1.json
  def destroy
    @slam_jam.destroy

    respond_with @slam_jam, location: admin_slam_jams_url
  end

  private

  def set_slam_jam
    @slam_jam = SlamJam.find(params[:id])
  end

  def slam_jam_params
    params.require(:slam_jam)
          .permit(:youtube_id, :artist, :title, :img_url, :approved)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  helper_method :current_or_guest_user
  def current_or_guest_user
    if session[:login].present?
      User.find_by(uuid: session[:login])
    else
      session_var = SecureRandom.uuid
      session[:login] = session_var
      User.create(uuid: session_var)
    end
  end
end

app/controllers/slam_jams_controller.rb
class SlamJamsController < ApplicationController
  def slam
    user = current_or_guest_user
    slam_jams = user.desirable_slam_jams

    @slam_jam = slam_jams.random
    user.slam!(@slam_jam)

    respond_to do |format|
      format.json { render json: @slam_jam }
    end
  end

  def like
    @slam_jam = SlamJam.find(params[:id])

    if params[:slam_jam][:liked] == 'true'
      current_or_guest_user.like(@slam_jam)
    else
      current_or_guest_user.unlike(@slam_jam)
    end

    respond_to do |format|
      format.js
    end
  end

  def dislike
    @slam_jam = SlamJam.find(params[:id])

    if params[:slam_jam][:disliked] == 'true'
      current_or_guest_user.dislike(@slam_jam)
    else
      current_or_guest_user.undislike(@slam_jam)
    end

    respond_to do |format|
      format.js
    end
  end
end

app/controllers/static_controller.rb
class StaticController < ApplicationController

  def home
    @slam_jam = SlamJam.all.first
  end
end

app/helpers/admin/slam_jams_helper.rb
module Admin::SlamJamsHelper
  def embed_youtube(youtube_id)
    params = { wmode: 'transport', html5: 1 }
    url = "http://www.youtube.com/embed/#{youtube_id}?#{params.to_query}"

    content_tag(:iframe, '',
                title: 'Slam Nation Station',
                width: 640,
                height: 480,
                type: 'text/html',
                frameborder: '0',
                src: url)
  end

  def admin_slam_jams_submit_url(slam_jam)
    if slam_jam.persisted?
      admin_slam_jam_url(slam_jam)
    else
      admin_slam_jams_url
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

  def ga_track_event(category, action, label)
    if Rails.env.production?
      category = escape_javascript(category)
      action = escape_javascript(action)
      label = escape_javascript(label)

      raw("_gaq.push(['_trackEvent', '#{category}', '#{action}', '#{label}']);")
    end
  end

end

app/helpers/slam_jams_helper.rb
module SlamJamsHelper
end

app/views/admin/slam_jams/_form.html.haml
= simple_form_for @slam_jam,
                  url: admin_slam_jams_submit_url(@slam_jam) do |f|
  = f.input :title
  = f.input :artist
  = f.input :youtube_id, label: 'YouTube ID'
  = f.input :img_url, label: 'Artist image URL'
  = f.input :approved
  = f.submit class: 'save-btn'

.show-slam-jam
  - if @slam_jam.youtube_id.present?
    .youtube-embed
      = embed_youtube(@slam_jam.youtube_id)

  - if @slam_jam.img_url.present?
    .artist-image
      = image_tag(@slam_jam.img_url)

app/views/admin/slam_jams/_slam_jam.html.haml
%tr{class: ('approved' if slam_jam.approved?)}
  %td= slam_jam.title
  %td= slam_jam.artist
  %td
    = link_to slam_jam.youtube_id,
              "http://youtube.com/watch?v=#{slam_jam.youtube_id}",
              target: '_blank'
  %td
    = link_to truncate(slam_jam.img_url),
              slam_jam.img_url,
              target: '_blank'

  %td.action
    = link_to 'Edit', edit_admin_slam_jam_path(slam_jam),
                      class: 'edit-btn'
  %td.action
    = link_to 'Destroy', admin_slam_jam_path(slam_jam),
                         method: :delete,
                         data: { confirm: 'Are you sure?' },
                         class: 'destroy-btn'

app/views/admin/slam_jams/edit.html.haml
.admin-panel
  .heading
    %h1 Edit Slam Jam

  .body
    = render 'form'

app/views/admin/slam_jams/index.html.haml
.admin-panel
  .heading
    %h1 Slam Jams

  .body
    = link_to 'Add a Slam Jam', new_admin_slam_jam_path,
                                class: 'new-btn'

    %table
      %tr
        %th Title
        %th Artist
        %th Youtube ID
        %th Artist Image URL
        %th
        %th

      = render @slam_jams

app/views/admin/slam_jams/new.html.haml
.admin-panel
  %header
    %h1 New Slam Jam

  .body
    = render 'form'

app/views/layouts/_ga.html.erb
<script type="text/javascript">
  var _gaq = _gaq || [];
  var pluginUrl = 
   '//www.google-analytics.com/plugins/ga/inpage_linkid.js';
  _gaq.push(['_require', 'inpage_linkid', pluginUrl]);
  _gaq.push(['_setAccount', 'UA-44998487-1']);
  _gaq.push(['_trackPageview']);

  (function() {
    var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
    ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
  })();
</script>

app/views/layouts/application.html.haml
!!! 5

%html
  %head
    %title Slam Station Nation

    = render :partial => 'layouts/ga' if Rails.env.production?

    = stylesheet_link_tag 'application', :media => 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags

  %body
    = yield

app/views/slam_jams/_rating.html.haml
.row
  .col-md-6
    = form_for :slam_jam, :remote => true, :url => like_slam_path(:id => slam_jam.id) do |f|
      = f.hidden_field :liked, :value => !current_or_guest_user.likes?(slam_jam)
      = f.submit "Rock it!", :id => "like_button", :class => [("active" if current_or_guest_user.likes?(slam_jam)), 'btn', 'btn-success']

  .col-md-6
    = form_for :slam_jam, :remote => true, :url => dislike_slam_path(:id => slam_jam.id) do |f|
      = f.hidden_field :disliked, :value => !current_or_guest_user.dislikes?(slam_jam)
      = f.submit "Drop it!", :id => "dislike_button", :class => [("active" if current_or_guest_user.dislikes?(slam_jam)), 'btn', 'btn-danger']

app/views/slam_jams/_slam_jam.html.haml
#rating
  = render :partial => "slam_jams/rating", :locals => { :slam_jam => slam_jam } 

app/views/slam_jams/dislike.js.erb
$('#rating').html("<%= j(render :partial => 'rating', :locals => { :slam_jam => @slam_jam}) %>"); 

app/views/slam_jams/like.js.erb
$('#rating').html("<%= j(render :partial => 'rating', :locals => { :slam_jam => @slam_jam}) %>"); 

app/views/slam_jams/slam.js.erb
<%= ga_track_event('slam_jam', 'slam', @slam_jam.title) %>

$('#slam_jam_video').html("<%= escape_javascript(render @slam_jam) %>");